version: '3'

services:
  mysql-dev:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_DATABASE: spring-reddit-clone
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3308:3306"